# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gui/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtSalida = QtWidgets.QTextEdit(self.centralwidget)
        self.txtSalida.setGeometry(QtCore.QRect(130, 50, 341, 151))
        self.txtSalida.setObjectName("txtSalida")
        self.btnHablar = QtWidgets.QPushButton(self.centralwidget)
        self.btnHablar.setGeometry(QtCore.QRect(90, 270, 141, 61))
        self.btnHablar.setObjectName("btnHablar")
        self.lblEstado = QtWidgets.QLabel(self.centralwidget)
        self.lblEstado.setGeometry(QtCore.QRect(290, 270, 161, 81))
        self.lblEstado.setText("")
        self.lblEstado.setObjectName("lblEstado")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnHablar.setText(_translate("MainWindow", "Hablar"))
