# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gui/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventanaPrincipal(object):
    def setupUi(self, ventanaPrincipal):
        ventanaPrincipal.setObjectName("ventanaPrincipal")
        ventanaPrincipal.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ventanaPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.chatView = QtWidgets.QTextBrowser(self.centralwidget)
        self.chatView.setGeometry(QtCore.QRect(150, 40, 256, 192))
        self.chatView.setObjectName("chatView")
        self.txtEntrada = QtWidgets.QTextEdit(self.centralwidget)
        self.txtEntrada.setGeometry(QtCore.QRect(160, 250, 251, 71))
        self.txtEntrada.setObjectName("txtEntrada")
        self.btnEnviar = QtWidgets.QPushButton(self.centralwidget)
        self.btnEnviar.setGeometry(QtCore.QRect(160, 340, 91, 41))
        self.btnEnviar.setObjectName("btnEnviar")
        self.chkLeer = QtWidgets.QCheckBox(self.centralwidget)
        self.chkLeer.setGeometry(QtCore.QRect(280, 340, 161, 51))
        self.chkLeer.setObjectName("chkLeer")
        self.btnHablar = QtWidgets.QPushButton(self.centralwidget)
        self.btnHablar.setGeometry(QtCore.QRect(160, 420, 75, 23))
        self.btnHablar.setObjectName("btnHablar")
        self.lblEstado = QtWidgets.QLabel(self.centralwidget)
        self.lblEstado.setGeometry(QtCore.QRect(290, 420, 81, 31))
        self.lblEstado.setObjectName("lblEstado")
        ventanaPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ventanaPrincipal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        ventanaPrincipal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ventanaPrincipal)
        self.statusbar.setObjectName("statusbar")
        ventanaPrincipal.setStatusBar(self.statusbar)

        self.retranslateUi(ventanaPrincipal)
        QtCore.QMetaObject.connectSlotsByName(ventanaPrincipal)

    def retranslateUi(self, ventanaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        ventanaPrincipal.setWindowTitle(_translate("ventanaPrincipal", "MainWindow"))
        self.btnEnviar.setText(_translate("ventanaPrincipal", "Enviar"))
        self.chkLeer.setText(_translate("ventanaPrincipal", "Leer respuestas en voz"))
        self.btnHablar.setText(_translate("ventanaPrincipal", "Hablar"))
        self.lblEstado.setText(_translate("ventanaPrincipal", "Estado"))
